package com.icss.mybatis.pojo;

public class Dept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.dept_id
     *
     * @mbggenerated Sun Jun 16 21:53:57 CST 2013
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.dept_name
     *
     * @mbggenerated Sun Jun 16 21:53:57 CST 2013
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.dept_loc
     *
     * @mbggenerated Sun Jun 16 21:53:57 CST 2013
     */
    private String deptLoc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.dept_id
     *
     * @return the value of dept.dept_id
     *
     * @mbggenerated Sun Jun 16 21:53:57 CST 2013
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.dept_id
     *
     * @param deptId the value for dept.dept_id
     *
     * @mbggenerated Sun Jun 16 21:53:57 CST 2013
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.dept_name
     *
     * @return the value of dept.dept_name
     *
     * @mbggenerated Sun Jun 16 21:53:57 CST 2013
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.dept_name
     *
     * @param deptName the value for dept.dept_name
     *
     * @mbggenerated Sun Jun 16 21:53:57 CST 2013
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.dept_loc
     *
     * @return the value of dept.dept_loc
     *
     * @mbggenerated Sun Jun 16 21:53:57 CST 2013
     */
    public String getDeptLoc() {
        return deptLoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.dept_loc
     *
     * @param deptLoc the value for dept.dept_loc
     *
     * @mbggenerated Sun Jun 16 21:53:57 CST 2013
     */
    public void setDeptLoc(String deptLoc) {
        this.deptLoc = deptLoc == null ? null : deptLoc.trim();
    }
}