package com.icss.mybatis.pojo;

public class Emp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.emp_id
     *
     * @mbggenerated Sun Jun 16 21:53:57 CST 2013
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.emp_name
     *
     * @mbggenerated Sun Jun 16 21:53:57 CST 2013
     */
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.emp_salary
     *
     * @mbggenerated Sun Jun 16 21:53:57 CST 2013
     */
    private Integer empSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.dept_id
     *
     * @mbggenerated Sun Jun 16 21:53:57 CST 2013
     */
    private Integer deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.emp_id
     *
     * @return the value of emp.emp_id
     *
     * @mbggenerated Sun Jun 16 21:53:57 CST 2013
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.emp_id
     *
     * @param empId the value for emp.emp_id
     *
     * @mbggenerated Sun Jun 16 21:53:57 CST 2013
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.emp_name
     *
     * @return the value of emp.emp_name
     *
     * @mbggenerated Sun Jun 16 21:53:57 CST 2013
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.emp_name
     *
     * @param empName the value for emp.emp_name
     *
     * @mbggenerated Sun Jun 16 21:53:57 CST 2013
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.emp_salary
     *
     * @return the value of emp.emp_salary
     *
     * @mbggenerated Sun Jun 16 21:53:57 CST 2013
     */
    public Integer getEmpSalary() {
        return empSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.emp_salary
     *
     * @param empSalary the value for emp.emp_salary
     *
     * @mbggenerated Sun Jun 16 21:53:57 CST 2013
     */
    public void setEmpSalary(Integer empSalary) {
        this.empSalary = empSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.dept_id
     *
     * @return the value of emp.dept_id
     *
     * @mbggenerated Sun Jun 16 21:53:57 CST 2013
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.dept_id
     *
     * @param deptId the value for emp.dept_id
     *
     * @mbggenerated Sun Jun 16 21:53:57 CST 2013
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }
}