package com.icss.mybatis.pojo;

import java.util.Date;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_id
     *
     * @mbggenerated Fri Jun 07 23:07:53 CST 2013
     */
    private Integer stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_name
     *
     * @mbggenerated Fri Jun 07 23:07:53 CST 2013
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_birthdate
     *
     * @mbggenerated Fri Jun 07 23:07:53 CST 2013
     */
    private Date stuBirthdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_phone
     *
     * @mbggenerated Fri Jun 07 23:07:53 CST 2013
     */
    private String stuPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_id
     *
     * @return the value of student.stu_id
     *
     * @mbggenerated Fri Jun 07 23:07:53 CST 2013
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_id
     *
     * @param stuId the value for student.stu_id
     *
     * @mbggenerated Fri Jun 07 23:07:53 CST 2013
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_name
     *
     * @return the value of student.stu_name
     *
     * @mbggenerated Fri Jun 07 23:07:53 CST 2013
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_name
     *
     * @param stuName the value for student.stu_name
     *
     * @mbggenerated Fri Jun 07 23:07:53 CST 2013
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_birthdate
     *
     * @return the value of student.stu_birthdate
     *
     * @mbggenerated Fri Jun 07 23:07:53 CST 2013
     */
    public Date getStuBirthdate() {
        return stuBirthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_birthdate
     *
     * @param stuBirthdate the value for student.stu_birthdate
     *
     * @mbggenerated Fri Jun 07 23:07:53 CST 2013
     */
    public void setStuBirthdate(Date stuBirthdate) {
        this.stuBirthdate = stuBirthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_phone
     *
     * @return the value of student.stu_phone
     *
     * @mbggenerated Fri Jun 07 23:07:53 CST 2013
     */
    public String getStuPhone() {
        return stuPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_phone
     *
     * @param stuPhone the value for student.stu_phone
     *
     * @mbggenerated Fri Jun 07 23:07:53 CST 2013
     */
    public void setStuPhone(String stuPhone) {
        this.stuPhone = stuPhone == null ? null : stuPhone.trim();
    }
}