package com.icss.hr.emp.po;

// Generated 2014-3-17 10:37:01 by Hibernate Tools 3.4.0.CR1

import java.sql.Date;

import com.icss.hr.dept.po.Dept;
import com.icss.hr.job.po.Job;

/**
 * Emp generated by hbm2java
 */
public class Emp implements java.io.Serializable {

	private Integer empId;
	private String empName;
	private String empEmail;
	private String empPhone;
	private Date empHiredate;
	private Job job;
	private Integer empSalary;
	private Dept dept;

	public Emp() {
	}

	public Emp(Integer empId) {
		this.empId = empId;
	}

	public Emp(String empName, String empEmail, String empPhone,
			Date empHiredate, Job job, Integer empSalary, Dept dept) {
		super();
		this.empName = empName;
		this.empEmail = empEmail;
		this.empPhone = empPhone;
		this.empHiredate = empHiredate;
		this.job = job;
		this.empSalary = empSalary;
		this.dept = dept;
	}

	public Emp(Integer empId, String empName, String empEmail, String empPhone,
			Date empHiredate, Job job, Integer empSalary, Dept dept) {
		super();
		this.empId = empId;
		this.empName = empName;
		this.empEmail = empEmail;
		this.empPhone = empPhone;
		this.empHiredate = empHiredate;
		this.job = job;
		this.empSalary = empSalary;
		this.dept = dept;
	}

	public Integer getEmpId() {
		return empId;
	}

	public void setEmpId(Integer empId) {
		this.empId = empId;
	}

	public String getEmpName() {
		return empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	public String getEmpEmail() {
		return empEmail;
	}

	public void setEmpEmail(String empEmail) {
		this.empEmail = empEmail;
	}

	public String getEmpPhone() {
		return empPhone;
	}

	public void setEmpPhone(String empPhone) {
		this.empPhone = empPhone;
	}

	public Date getEmpHiredate() {
		return empHiredate;
	}

	public void setEmpHiredate(Date empHiredate) {
		this.empHiredate = empHiredate;
	}

	public Job getJob() {
		return job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	public Integer getEmpSalary() {
		return empSalary;
	}

	public void setEmpSalary(Integer empSalary) {
		this.empSalary = empSalary;
	}

	public Dept getDept() {
		return dept;
	}

	public void setDept(Dept dept) {
		this.dept = dept;
	}

	@Override
	public String toString() {
		return "Emp [empId=" + empId + ", empName=" + empName + ", empEmail="
				+ empEmail + ", empPhone=" + empPhone + ", empHiredate="
				+ empHiredate + ", job=" + job + ", empSalary=" + empSalary
				+ ", dept=" + dept + "]";
	}
		
}