package com.icss.oa.system.pojo;

import java.util.Date;

public class Bbs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BBS.BBS_ID
     *
     * @mbggenerated Tue Jul 08 17:25:25 CST 2014
     */
    private Integer bbsId;
    public String getTime() {
		return time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	private String time;
	

    public Bbs() {
		super();
	}

	public Bbs(Integer bbsId, String bbsTitle, Short bbsTop, String bbsCont) {
		super();
		this.bbsId = bbsId;
		this.bbsTitle = bbsTitle;
		this.bbsTop = bbsTop;
		this.bbsCont = bbsCont;
	}

	public Bbs(String bbsTitle, Short bbsTop, String bbsCont) {
		super();
		this.bbsTitle = bbsTitle;
		this.bbsTop = bbsTop;
		this.bbsCont = bbsCont;
	}

	public Bbs(Integer bbsId, String bbsTitle, Date bbsTime, Short bbsTop,
			String bbsCont) {
		super();
		this.bbsId = bbsId;
		this.bbsTitle = bbsTitle;
		this.bbsTime = bbsTime;
		this.bbsTop = bbsTop;
		this.bbsCont = bbsCont;
	}

	@Override
	public String toString() {
		return "Bbs [bbsId=" + bbsId + ", bbsTitle=" + bbsTitle + ", bbsTime="
				+ bbsTime + ", bbsTop=" + bbsTop + ", bbsCont=" + bbsCont + "]";
	}


	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BBS.BBS_TITLE
     *
     * @mbggenerated Tue Jul 08 17:25:25 CST 2014
     */
    private String bbsTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BBS.BBS_TIME
     *
     * @mbggenerated Tue Jul 08 17:25:25 CST 2014
     */
    private Date bbsTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BBS.BBS_TOP
     *
     * @mbggenerated Tue Jul 08 17:25:25 CST 2014
     */
    private Short bbsTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BBS.BBS_CONT
     *
     * @mbggenerated Tue Jul 08 17:25:25 CST 2014
     */
    private String bbsCont;


	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BBS.BBS_ID
     *
     * @return the value of BBS.BBS_ID
     *
     * @mbggenerated Tue Jul 08 17:25:25 CST 2014
     */
    public Integer getBbsId() {
        return bbsId;
    }

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BBS.BBS_ID
     *
     * @param bbsId the value for BBS.BBS_ID
     *
     * @mbggenerated Tue Jul 08 17:25:25 CST 2014
     */
    public void setBbsId(Integer bbsId) {
        this.bbsId = bbsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BBS.BBS_TITLE
     *
     * @return the value of BBS.BBS_TITLE
     *
     * @mbggenerated Tue Jul 08 17:25:25 CST 2014
     */
    public String getBbsTitle() {
        return bbsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BBS.BBS_TITLE
     *
     * @param bbsTitle the value for BBS.BBS_TITLE
     *
     * @mbggenerated Tue Jul 08 17:25:25 CST 2014
     */
    public void setBbsTitle(String bbsTitle) {
        this.bbsTitle = bbsTitle == null ? null : bbsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BBS.BBS_TIME
     *
     * @return the value of BBS.BBS_TIME
     *
     * @mbggenerated Tue Jul 08 17:25:25 CST 2014
     */
    public Date getBbsTime() {
        return bbsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BBS.BBS_TIME
     *
     * @param bbsTime the value for BBS.BBS_TIME
     *
     * @mbggenerated Tue Jul 08 17:25:25 CST 2014
     */
    public void setBbsTime(Date bbsTime) {
        this.bbsTime = bbsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BBS.BBS_TOP
     *
     * @return the value of BBS.BBS_TOP
     *
     * @mbggenerated Tue Jul 08 17:25:25 CST 2014
     */
    public Short getBbsTop() {
        return bbsTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BBS.BBS_TOP
     *
     * @param bbsTop the value for BBS.BBS_TOP
     *
     * @mbggenerated Tue Jul 08 17:25:25 CST 2014
     */
    public void setBbsTop(Short bbsTop) {
        this.bbsTop = bbsTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BBS.BBS_CONT
     *
     * @return the value of BBS.BBS_CONT
     *
     * @mbggenerated Tue Jul 08 17:25:25 CST 2014
     */
    public String getBbsCont() {
        return bbsCont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BBS.BBS_CONT
     *
     * @param bbsCont the value for BBS.BBS_CONT
     *
     * @mbggenerated Tue Jul 08 17:25:25 CST 2014
     */
    public void setBbsCont(String bbsCont) {
        this.bbsCont = bbsCont == null ? null : bbsCont.trim();
    }
}