package com.icss.oa.system.pojo;

public class Dept {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column DEPT.DEPT_ID
	 * 
	 * @mbggenerated Fri Jun 20 14:58:15 CST 2014
	 */
	private Integer deptId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column DEPT.DEPT_NAME
	 * 
	 * @mbggenerated Fri Jun 20 14:58:15 CST 2014
	 */
	private String deptName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column DEPT.DEPT_LOC
	 * 
	 * @mbggenerated Fri Jun 20 14:58:15 CST 2014
	 */
	private String deptLoc;

	public Dept() {
		super();
	}

	public Dept(String deptName, String deptLoc) {
		super();
		this.deptName = deptName;
		this.deptLoc = deptLoc;
	}

	public Dept(Integer deptId, String deptName, String deptLoc) {
		super();
		this.deptId = deptId;
		this.deptName = deptName;
		this.deptLoc = deptLoc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column DEPT.DEPT_ID
	 * 
	 * @return the value of DEPT.DEPT_ID
	 * 
	 * @mbggenerated Fri Jun 20 14:58:15 CST 2014
	 */
	public Integer getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column DEPT.DEPT_ID
	 * 
	 * @param deptId
	 *            the value for DEPT.DEPT_ID
	 * 
	 * @mbggenerated Fri Jun 20 14:58:15 CST 2014
	 */
	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column DEPT.DEPT_NAME
	 * 
	 * @return the value of DEPT.DEPT_NAME
	 * 
	 * @mbggenerated Fri Jun 20 14:58:15 CST 2014
	 */
	public String getDeptName() {
		return deptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column DEPT.DEPT_NAME
	 * 
	 * @param deptName
	 *            the value for DEPT.DEPT_NAME
	 * 
	 * @mbggenerated Fri Jun 20 14:58:15 CST 2014
	 */
	public void setDeptName(String deptName) {
		this.deptName = deptName == null ? null : deptName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column DEPT.DEPT_LOC
	 * 
	 * @return the value of DEPT.DEPT_LOC
	 * 
	 * @mbggenerated Fri Jun 20 14:58:15 CST 2014
	 */
	public String getDeptLoc() {
		return deptLoc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column DEPT.DEPT_LOC
	 * 
	 * @param deptLoc
	 *            the value for DEPT.DEPT_LOC
	 * 
	 * @mbggenerated Fri Jun 20 14:58:15 CST 2014
	 */
	public void setDeptLoc(String deptLoc) {
		this.deptLoc = deptLoc == null ? null : deptLoc.trim();
	}

	@Override
	public String toString() {
		return "Dept [deptId=" + deptId + ", deptName=" + deptName
				+ ", deptLoc=" + deptLoc + "]";
	}

}