package com.icss.oa.system.pojo;

import java.util.Date;

public class Emp {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column EMP.EMP_ID
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	private Integer empId;
	private Integer ur;
	private Integer isVisible; 
	
	public Integer getIsVisible() {
		return isVisible;
	}

	public void setIsVisible(Integer isVisible) {
		this.isVisible = isVisible;
	}

	public Integer getUr() {
		return ur;
	}

	public void setUr(Integer ur) {
		this.ur = ur;
	}

	private Integer roleId;

	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column EMP.EMP_NAME
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	private String empName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column EMP.USERNAME
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	private String username;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column EMP.PASSWORD
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	private String password;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column EMP.EMP_SEX
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	private String empSex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column EMP.EMP_BIRTHDATE
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	private Date empBirthdate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column EMP.EMP_EMAIL
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	private String empEmail;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column EMP.EMP_PHONE
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	private String empPhone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column EMP.EMP_MOBILE
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	private String empMobile;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column EMP.EMP_ADDRESS
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	private String empAddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column EMP.EMP_INFO
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	private String empInfo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column EMP.DEPT_ID
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	private Integer deptId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column EMP.JOB_ID
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	private Integer jobId;

	public Emp() {
		super();
	}

	public Emp(String empName, String username, String password, String empSex,
			Date empBirthdate, String empEmail, String empPhone,
			String empMobile, String empAddress, String empInfo,
			Integer deptId, Integer jobId) {
		super();
		this.empName = empName;
		this.username = username;
		this.password = password;
		this.empSex = empSex;
		this.empBirthdate = empBirthdate;
		this.empEmail = empEmail;
		this.empPhone = empPhone;
		this.empMobile = empMobile;
		this.empAddress = empAddress;
		this.empInfo = empInfo;
		this.deptId = deptId;
		this.jobId = jobId;
	}

	public Emp(Integer empId, String empName, String username, String password,
			String empSex, Date empBirthdate, String empEmail, String empPhone,
			String empMobile, String empAddress, String empInfo,
			Integer deptId, Integer jobId) {
		super();
		this.empId = empId;
		this.empName = empName;
		this.username = username;
		this.password = password;
		this.empSex = empSex;
		this.empBirthdate = empBirthdate;
		this.empEmail = empEmail;
		this.empPhone = empPhone;
		this.empMobile = empMobile;
		this.empAddress = empAddress;
		this.empInfo = empInfo;
		this.deptId = deptId;
		this.jobId = jobId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column EMP.EMP_ID
	 * 
	 * @return the value of EMP.EMP_ID
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public Integer getEmpId() {
		return empId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column EMP.EMP_ID
	 * 
	 * @param empId
	 *            the value for EMP.EMP_ID
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public void setEmpId(Integer empId) {
		this.empId = empId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column EMP.EMP_NAME
	 * 
	 * @return the value of EMP.EMP_NAME
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public String getEmpName() {
		return empName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column EMP.EMP_NAME
	 * 
	 * @param empName
	 *            the value for EMP.EMP_NAME
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public void setEmpName(String empName) {
		this.empName = empName == null ? null : empName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column EMP.USERNAME
	 * 
	 * @return the value of EMP.USERNAME
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column EMP.USERNAME
	 * 
	 * @param username
	 *            the value for EMP.USERNAME
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column EMP.PASSWORD
	 * 
	 * @return the value of EMP.PASSWORD
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column EMP.PASSWORD
	 * 
	 * @param password
	 *            the value for EMP.PASSWORD
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column EMP.EMP_SEX
	 * 
	 * @return the value of EMP.EMP_SEX
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public String getEmpSex() {
		return empSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column EMP.EMP_SEX
	 * 
	 * @param empSex
	 *            the value for EMP.EMP_SEX
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public void setEmpSex(String empSex) {
		this.empSex = empSex == null ? null : empSex.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column EMP.EMP_BIRTHDATE
	 * 
	 * @return the value of EMP.EMP_BIRTHDATE
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public Date getEmpBirthdate() {
		return empBirthdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column EMP.EMP_BIRTHDATE
	 * 
	 * @param empBirthdate
	 *            the value for EMP.EMP_BIRTHDATE
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public void setEmpBirthdate(Date empBirthdate) {
		this.empBirthdate = empBirthdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column EMP.EMP_EMAIL
	 * 
	 * @return the value of EMP.EMP_EMAIL
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public String getEmpEmail() {
		return empEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column EMP.EMP_EMAIL
	 * 
	 * @param empEmail
	 *            the value for EMP.EMP_EMAIL
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public void setEmpEmail(String empEmail) {
		this.empEmail = empEmail == null ? null : empEmail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column EMP.EMP_PHONE
	 * 
	 * @return the value of EMP.EMP_PHONE
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public String getEmpPhone() {
		return empPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column EMP.EMP_PHONE
	 * 
	 * @param empPhone
	 *            the value for EMP.EMP_PHONE
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public void setEmpPhone(String empPhone) {
		this.empPhone = empPhone == null ? null : empPhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column EMP.EMP_MOBILE
	 * 
	 * @return the value of EMP.EMP_MOBILE
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public String getEmpMobile() {
		return empMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column EMP.EMP_MOBILE
	 * 
	 * @param empMobile
	 *            the value for EMP.EMP_MOBILE
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public void setEmpMobile(String empMobile) {
		this.empMobile = empMobile == null ? null : empMobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column EMP.EMP_ADDRESS
	 * 
	 * @return the value of EMP.EMP_ADDRESS
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public String getEmpAddress() {
		return empAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column EMP.EMP_ADDRESS
	 * 
	 * @param empAddress
	 *            the value for EMP.EMP_ADDRESS
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public void setEmpAddress(String empAddress) {
		this.empAddress = empAddress == null ? null : empAddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column EMP.EMP_INFO
	 * 
	 * @return the value of EMP.EMP_INFO
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public String getEmpInfo() {
		return empInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column EMP.EMP_INFO
	 * 
	 * @param empInfo
	 *            the value for EMP.EMP_INFO
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public void setEmpInfo(String empInfo) {
		this.empInfo = empInfo == null ? null : empInfo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column EMP.DEPT_ID
	 * 
	 * @return the value of EMP.DEPT_ID
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public Integer getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column EMP.DEPT_ID
	 * 
	 * @param deptId
	 *            the value for EMP.DEPT_ID
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column EMP.JOB_ID
	 * 
	 * @return the value of EMP.JOB_ID
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public Integer getJobId() {
		return jobId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column EMP.JOB_ID
	 * 
	 * @param jobId
	 *            the value for EMP.JOB_ID
	 * 
	 * @mbggenerated Tue Jun 24 11:25:19 CST 2014
	 */
	public void setJobId(Integer jobId) {
		this.jobId = jobId;
	}

	@Override
	public String toString() {
		return "Emp [empId=" + empId + ", empName=" + empName + ", username="
				+ username + ", password=" + password + ", empSex=" + empSex
				+ ", empBirthdate=" + empBirthdate + ", empEmail=" + empEmail
				+ ", empPhone=" + empPhone + ", empMobile=" + empMobile
				+ ", empAddress=" + empAddress + ", empInfo=" + empInfo
				+ ", deptId=" + deptId + ", jobId=" + jobId + "]";
	}

}