package com.icss.oa.system.pojo;

public class Job {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JOB.JOB_ID
	 * 
	 * @mbggenerated Mon Jun 23 16:43:18 CST 2014
	 */
	private Integer jobId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column JOB.JOB_NAME
	 * 
	 * @mbggenerated Mon Jun 23 16:43:18 CST 2014
	 */
	private String jobName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JOB.JOB_ID
	 * 
	 * @return the value of JOB.JOB_ID
	 * 
	 * @mbggenerated Mon Jun 23 16:43:18 CST 2014
	 */
	public Integer getJobId() {
		return jobId;
	}

	public Job() {
		super();
	}

	public Job(String jobName) {
		super();
		this.jobName = jobName;
	}

	public Job(Integer jobId, String jobName) {
		super();
		this.jobId = jobId;
		this.jobName = jobName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JOB.JOB_ID
	 * 
	 * @param jobId
	 *            the value for JOB.JOB_ID
	 * 
	 * @mbggenerated Mon Jun 23 16:43:18 CST 2014
	 */
	public void setJobId(Integer jobId) {
		this.jobId = jobId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column JOB.JOB_NAME
	 * 
	 * @return the value of JOB.JOB_NAME
	 * 
	 * @mbggenerated Mon Jun 23 16:43:18 CST 2014
	 */
	public String getJobName() {
		return jobName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column JOB.JOB_NAME
	 * 
	 * @param jobName
	 *            the value for JOB.JOB_NAME
	 * 
	 * @mbggenerated Mon Jun 23 16:43:18 CST 2014
	 */
	public void setJobName(String jobName) {
		this.jobName = jobName == null ? null : jobName.trim();
	}

	@Override
	public String toString() {
		return "Job [jobId=" + jobId + ", jobName=" + jobName + "]";
	}

}