package com.icss.oa.system.pojo;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.ROLE_ID
     *
     * @mbggenerated Fri Jul 18 15:00:44 CST 2014
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.ROLE_NAME
     *
     * @mbggenerated Fri Jul 18 15:00:44 CST 2014
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.ROLE_INFO
     *
     * @mbggenerated Fri Jul 18 15:00:44 CST 2014
     */
    private String roleInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.ROLE_ID
     *
     * @return the value of ROLE.ROLE_ID
     *
     * @mbggenerated Fri Jul 18 15:00:44 CST 2014
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.ROLE_ID
     *
     * @param roleId the value for ROLE.ROLE_ID
     *
     * @mbggenerated Fri Jul 18 15:00:44 CST 2014
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.ROLE_NAME
     *
     * @return the value of ROLE.ROLE_NAME
     *
     * @mbggenerated Fri Jul 18 15:00:44 CST 2014
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.ROLE_NAME
     *
     * @param roleName the value for ROLE.ROLE_NAME
     *
     * @mbggenerated Fri Jul 18 15:00:44 CST 2014
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.ROLE_INFO
     *
     * @return the value of ROLE.ROLE_INFO
     *
     * @mbggenerated Fri Jul 18 15:00:44 CST 2014
     */
    public String getRoleInfo() {
        return roleInfo;
    }

    @Override
	public String toString() {
		return "Role [roleId=" + roleId + ", roleName=" + roleName
				+ ", roleInfo=" + roleInfo + "]";
	}

	public Role() {
		super();
	}

	public Role(String roleName, String roleInfo) {
		super();
		this.roleName = roleName;
		this.roleInfo = roleInfo;
	}

	public Role(Integer roleId, String roleName, String roleInfo) {
		super();
		this.roleId = roleId;
		this.roleName = roleName;
		this.roleInfo = roleInfo;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.ROLE_INFO
     *
     * @param roleInfo the value for ROLE.ROLE_INFO
     *
     * @mbggenerated Fri Jul 18 15:00:44 CST 2014
     */
    public void setRoleInfo(String roleInfo) {
        this.roleInfo = roleInfo == null ? null : roleInfo.trim();
    }
}