package com.icss.oa.assign.pojo;

public class Assigncom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSIGNCOM.ASSIGNCOM_ID
     *
     * @mbggenerated Fri Jun 27 15:07:30 CST 2014
     */
    private Integer assigncomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSIGNCOM.ASSIGNCOM_NAME
     *
     * @mbggenerated Fri Jun 27 15:07:30 CST 2014
     */
    private String assigncomName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSIGNCOM.ASSIGNCOM_CON
     *
     * @mbggenerated Fri Jun 27 15:07:30 CST 2014
     */
    private String assigncomCon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSIGNCOM.ASSIGNCOM_JOBCATEGORY
     *
     * @mbggenerated Fri Jun 27 15:07:30 CST 2014
     */
    private String assigncomJobcategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSIGNCOM.ASSIGNCOM_JOBS
     *
     * @mbggenerated Fri Jun 27 15:07:30 CST 2014
     */
    private String assigncomJobs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSIGNCOM.ASSIGNCOM_SAL
     *
     * @mbggenerated Fri Jun 27 15:07:30 CST 2014
     */
    private int assigncomSal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSIGNCOM.ASSIGNCOM_REMARKS
     *
     * @mbggenerated Fri Jun 27 15:07:30 CST 2014
     */
    private String assigncomRemarks;
    
    

    public Assigncom() {
		super();
	}
    
    

	public Assigncom(String assigncomName, String assigncomCon,
			String assigncomJobcategory, String assigncomJobs,
			int assigncomSal, String assigncomRemarks) {
		super();
		this.assigncomName = assigncomName;
		this.assigncomCon = assigncomCon;
		this.assigncomJobcategory = assigncomJobcategory;
		this.assigncomJobs = assigncomJobs;
		this.assigncomSal = assigncomSal;
		this.assigncomRemarks = assigncomRemarks;
	}
	
	
	public Assigncom(Integer assigncomId, String assigncomName,
			String assigncomCon, String assigncomJobcategory,
			String assigncomJobs, int assigncomSal, String assigncomRemarks) {
		super();
		this.assigncomId = assigncomId;
		this.assigncomName = assigncomName;
		this.assigncomCon = assigncomCon;
		this.assigncomJobcategory = assigncomJobcategory;
		this.assigncomJobs = assigncomJobs;
		this.assigncomSal = assigncomSal;
		this.assigncomRemarks = assigncomRemarks;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSIGNCOM.ASSIGNCOM_ID
     *
     * @return the value of ASSIGNCOM.ASSIGNCOM_ID
     *
     * @mbggenerated Fri Jun 27 15:07:30 CST 2014
     */
    public Integer getAssigncomId() {
        return assigncomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSIGNCOM.ASSIGNCOM_ID
     *
     * @param assigncomId the value for ASSIGNCOM.ASSIGNCOM_ID
     *
     * @mbggenerated Fri Jun 27 15:07:30 CST 2014
     */
    public void setAssigncomId(Integer assigncomId) {
        this.assigncomId = assigncomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSIGNCOM.ASSIGNCOM_NAME
     *
     * @return the value of ASSIGNCOM.ASSIGNCOM_NAME
     *
     * @mbggenerated Fri Jun 27 15:07:30 CST 2014
     */
    public String getAssigncomName() {
        return assigncomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSIGNCOM.ASSIGNCOM_NAME
     *
     * @param assigncomName the value for ASSIGNCOM.ASSIGNCOM_NAME
     *
     * @mbggenerated Fri Jun 27 15:07:30 CST 2014
     */
    public void setAssigncomName(String assigncomName) {
        this.assigncomName = assigncomName == null ? null : assigncomName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSIGNCOM.ASSIGNCOM_CON
     *
     * @return the value of ASSIGNCOM.ASSIGNCOM_CON
     *
     * @mbggenerated Fri Jun 27 15:07:30 CST 2014
     */
    public String getAssigncomCon() {
        return assigncomCon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSIGNCOM.ASSIGNCOM_CON
     *
     * @param assigncomCon the value for ASSIGNCOM.ASSIGNCOM_CON
     *
     * @mbggenerated Fri Jun 27 15:07:30 CST 2014
     */
    public void setAssigncomCon(String assigncomCon) {
        this.assigncomCon = assigncomCon == null ? null : assigncomCon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSIGNCOM.ASSIGNCOM_JOBCATEGORY
     *
     * @return the value of ASSIGNCOM.ASSIGNCOM_JOBCATEGORY
     *
     * @mbggenerated Fri Jun 27 15:07:30 CST 2014
     */
    public String getAssigncomJobcategory() {
        return assigncomJobcategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSIGNCOM.ASSIGNCOM_JOBCATEGORY
     *
     * @param assigncomJobcategory the value for ASSIGNCOM.ASSIGNCOM_JOBCATEGORY
     *
     * @mbggenerated Fri Jun 27 15:07:30 CST 2014
     */
    public void setAssigncomJobcategory(String assigncomJobcategory) {
        this.assigncomJobcategory = assigncomJobcategory == null ? null : assigncomJobcategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSIGNCOM.ASSIGNCOM_JOBS
     *
     * @return the value of ASSIGNCOM.ASSIGNCOM_JOBS
     *
     * @mbggenerated Fri Jun 27 15:07:30 CST 2014
     */
    public String getAssigncomJobs() {
        return assigncomJobs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSIGNCOM.ASSIGNCOM_JOBS
     *
     * @param assigncomJobs the value for ASSIGNCOM.ASSIGNCOM_JOBS
     *
     * @mbggenerated Fri Jun 27 15:07:30 CST 2014
     */
    public void setAssigncomJobs(String assigncomJobs) {
        this.assigncomJobs = assigncomJobs == null ? null : assigncomJobs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSIGNCOM.ASSIGNCOM_SAL
     *
     * @return the value of ASSIGNCOM.ASSIGNCOM_SAL
     *
     * @mbggenerated Fri Jun 27 15:07:30 CST 2014
     */
    public int getAssigncomSal() {
        return assigncomSal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSIGNCOM.ASSIGNCOM_SAL
     *
     * @param assigncomSal the value for ASSIGNCOM.ASSIGNCOM_SAL
     *
     * @mbggenerated Fri Jun 27 15:07:30 CST 2014
     */
    public void setAssigncomSal(int assigncomSal) {
        this.assigncomSal = assigncomSal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSIGNCOM.ASSIGNCOM_REMARKS
     *
     * @return the value of ASSIGNCOM.ASSIGNCOM_REMARKS
     *
     * @mbggenerated Fri Jun 27 15:07:30 CST 2014
     */
    public String getAssigncomRemarks() {
        return assigncomRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSIGNCOM.ASSIGNCOM_REMARKS
     *
     * @param assigncomRemarks the value for ASSIGNCOM.ASSIGNCOM_REMARKS
     *
     * @mbggenerated Fri Jun 27 15:07:30 CST 2014
     */
    public void setAssigncomRemarks(String assigncomRemarks) {
        this.assigncomRemarks = assigncomRemarks == null ? null : assigncomRemarks.trim();
    }
}