package com.icss.oa.assign.pojo;

import java.util.Date;

public class Exphistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPHISTORY.EXPHISTORY_ID1
     *
     * @mbggenerated Wed Jul 02 08:31:17 CST 2014
     */
    private Integer exphistoryId1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPHISTORY.EXPHISTORY_ID2
     *
     * @mbggenerated Wed Jul 02 08:31:17 CST 2014
     */
    private Integer exphistoryId2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPHISTORY.EXPHISTORY_CON
     *
     * @mbggenerated Wed Jul 02 08:31:17 CST 2014
     */
    private String exphistoryCon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPHISTORY.EXPHISTORY_COM
     *
     * @mbggenerated Wed Jul 02 08:31:17 CST 2014
     */
    private String exphistoryCom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPHISTORY.EXPHISTORY_BEDATE
     *
     * @mbggenerated Wed Jul 02 08:31:17 CST 2014
     */
    private Date exphistoryBedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPHISTORY.EXPHISTORY_ENDATE
     *
     * @mbggenerated Wed Jul 02 08:31:17 CST 2014
     */
    private Date exphistoryEndate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPHISTORY.EXPHISTORY_SAL
     *
     * @mbggenerated Wed Jul 02 08:31:17 CST 2014
     */
    private Integer exphistorySal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPHISTORY.EXPHISTORY_REM
     *
     * @mbggenerated Wed Jul 02 08:31:17 CST 2014
     */
    private String exphistoryRem;
    
    

    public Exphistory() {
		super();
	}
    
    

	public Exphistory(Integer exphistoryId2, String exphistoryCon,
			String exphistoryCom, Date exphistoryBedate, Date exphistoryEndate,
			Integer exphistorySal, String exphistoryRem) {
		super();
		this.exphistoryId2 = exphistoryId2;
		this.exphistoryCon = exphistoryCon;
		this.exphistoryCom = exphistoryCom;
		this.exphistoryBedate = exphistoryBedate;
		this.exphistoryEndate = exphistoryEndate;
		this.exphistorySal = exphistorySal;
		this.exphistoryRem = exphistoryRem;
	}


	public Exphistory(Integer exphistoryId1, Integer exphistoryId2,
			String exphistoryCon, String exphistoryCom, Date exphistoryBedate,
			Date exphistoryEndate, Integer exphistorySal, String exphistoryRem) {
		super();
		this.exphistoryId1 = exphistoryId1;
		this.exphistoryId2 = exphistoryId2;
		this.exphistoryCon = exphistoryCon;
		this.exphistoryCom = exphistoryCom;
		this.exphistoryBedate = exphistoryBedate;
		this.exphistoryEndate = exphistoryEndate;
		this.exphistorySal = exphistorySal;
		this.exphistoryRem = exphistoryRem;
	}



	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPHISTORY.EXPHISTORY_ID1
     *
     * @return the value of EXPHISTORY.EXPHISTORY_ID1
     *
     * @mbggenerated Wed Jul 02 08:31:17 CST 2014
     */
    public Integer getExphistoryId1() {
        return exphistoryId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPHISTORY.EXPHISTORY_ID1
     *
     * @param exphistoryId1 the value for EXPHISTORY.EXPHISTORY_ID1
     *
     * @mbggenerated Wed Jul 02 08:31:17 CST 2014
     */
    public void setExphistoryId1(Integer exphistoryId1) {
        this.exphistoryId1 = exphistoryId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPHISTORY.EXPHISTORY_ID2
     *
     * @return the value of EXPHISTORY.EXPHISTORY_ID2
     *
     * @mbggenerated Wed Jul 02 08:31:17 CST 2014
     */
    public Integer getExphistoryId2() {
        return exphistoryId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPHISTORY.EXPHISTORY_ID2
     *
     * @param exphistoryId2 the value for EXPHISTORY.EXPHISTORY_ID2
     *
     * @mbggenerated Wed Jul 02 08:31:17 CST 2014
     */
    public void setExphistoryId2(Integer exphistoryId2) {
        this.exphistoryId2 = exphistoryId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPHISTORY.EXPHISTORY_CON
     *
     * @return the value of EXPHISTORY.EXPHISTORY_CON
     *
     * @mbggenerated Wed Jul 02 08:31:17 CST 2014
     */
    public String getExphistoryCon() {
        return exphistoryCon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPHISTORY.EXPHISTORY_CON
     *
     * @param exphistoryCon the value for EXPHISTORY.EXPHISTORY_CON
     *
     * @mbggenerated Wed Jul 02 08:31:17 CST 2014
     */
    public void setExphistoryCon(String exphistoryCon) {
        this.exphistoryCon = exphistoryCon == null ? null : exphistoryCon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPHISTORY.EXPHISTORY_COM
     *
     * @return the value of EXPHISTORY.EXPHISTORY_COM
     *
     * @mbggenerated Wed Jul 02 08:31:17 CST 2014
     */
    public String getExphistoryCom() {
        return exphistoryCom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPHISTORY.EXPHISTORY_COM
     *
     * @param exphistoryCom the value for EXPHISTORY.EXPHISTORY_COM
     *
     * @mbggenerated Wed Jul 02 08:31:17 CST 2014
     */
    public void setExphistoryCom(String exphistoryCom) {
        this.exphistoryCom = exphistoryCom == null ? null : exphistoryCom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPHISTORY.EXPHISTORY_BEDATE
     *
     * @return the value of EXPHISTORY.EXPHISTORY_BEDATE
     *
     * @mbggenerated Wed Jul 02 08:31:17 CST 2014
     */
    public Date getExphistoryBedate() {
        return exphistoryBedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPHISTORY.EXPHISTORY_BEDATE
     *
     * @param exphistoryBedate the value for EXPHISTORY.EXPHISTORY_BEDATE
     *
     * @mbggenerated Wed Jul 02 08:31:17 CST 2014
     */
    public void setExphistoryBedate(Date exphistoryBedate) {
        this.exphistoryBedate = exphistoryBedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPHISTORY.EXPHISTORY_ENDATE
     *
     * @return the value of EXPHISTORY.EXPHISTORY_ENDATE
     *
     * @mbggenerated Wed Jul 02 08:31:17 CST 2014
     */
    public Date getExphistoryEndate() {
        return exphistoryEndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPHISTORY.EXPHISTORY_ENDATE
     *
     * @param exphistoryEndate the value for EXPHISTORY.EXPHISTORY_ENDATE
     *
     * @mbggenerated Wed Jul 02 08:31:17 CST 2014
     */
    public void setExphistoryEndate(Date exphistoryEndate) {
        this.exphistoryEndate = exphistoryEndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPHISTORY.EXPHISTORY_SAL
     *
     * @return the value of EXPHISTORY.EXPHISTORY_SAL
     *
     * @mbggenerated Wed Jul 02 08:31:17 CST 2014
     */
    public Integer getExphistorySal() {
        return exphistorySal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPHISTORY.EXPHISTORY_SAL
     *
     * @param exphistorySal the value for EXPHISTORY.EXPHISTORY_SAL
     *
     * @mbggenerated Wed Jul 02 08:31:17 CST 2014
     */
    public void setExphistorySal(Integer exphistorySal) {
        this.exphistorySal = exphistorySal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPHISTORY.EXPHISTORY_REM
     *
     * @return the value of EXPHISTORY.EXPHISTORY_REM
     *
     * @mbggenerated Wed Jul 02 08:31:17 CST 2014
     */
    public String getExphistoryRem() {
        return exphistoryRem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPHISTORY.EXPHISTORY_REM
     *
     * @param exphistoryRem the value for EXPHISTORY.EXPHISTORY_REM
     *
     * @mbggenerated Wed Jul 02 08:31:17 CST 2014
     */
    public void setExphistoryRem(String exphistoryRem) {
        this.exphistoryRem = exphistoryRem == null ? null : exphistoryRem.trim();
    }



	@Override
	public String toString() {
		return "Exphistory [exphistoryId1=" + exphistoryId1
				+ ", exphistoryId2=" + exphistoryId2 + ", exphistoryCon="
				+ exphistoryCon + ", exphistoryCom=" + exphistoryCom
				+ ", exphistoryBedate=" + exphistoryBedate
				+ ", exphistoryEndate=" + exphistoryEndate + ", exphistorySal="
				+ exphistorySal + ", exphistoryRem=" + exphistoryRem + "]";
	}
    
    
    
}