package com.icss.oa.work.pojo;

import java.util.Date;

public class Schedule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHEDULE.SCHEDULE_ID
     *
     * @mbggenerated Wed Jul 09 14:57:48 CST 2014
     */
    private Integer scheduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHEDULE.SCHEDULE_EMPID
     *
     * @mbggenerated Wed Jul 09 14:57:48 CST 2014
     */
    private Integer scheduleEmpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHEDULE.SCHEDULE_EMPNAME
     *
     * @mbggenerated Wed Jul 09 14:57:48 CST 2014
     */
    private String scheduleEmpname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHEDULE.SCHEDULE_SCH
     *
     * @mbggenerated Wed Jul 09 14:57:48 CST 2014
     */
    private String scheduleSch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHEDULE.SCHEDULE_BEDATE
     *
     * @mbggenerated Wed Jul 09 14:57:48 CST 2014
     */
    private Date scheduleBedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHEDULE.SCHEDULE_ENDATE
     *
     * @mbggenerated Wed Jul 09 14:57:48 CST 2014
     */
    private Date scheduleEndate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHEDULE.SCHEDULE_REM
     *
     * @mbggenerated Wed Jul 09 14:57:48 CST 2014
     */
    private String scheduleRem;
    
    
    public Schedule() {
		super();
	}
    
    

	public Schedule(Integer scheduleEmpid, String scheduleEmpname,
			String scheduleSch, Date scheduleBedate, Date scheduleEndate,
			String scheduleRem) {
		super();
		this.scheduleEmpid = scheduleEmpid;
		this.scheduleEmpname = scheduleEmpname;
		this.scheduleSch = scheduleSch;
		this.scheduleBedate = scheduleBedate;
		this.scheduleEndate = scheduleEndate;
		this.scheduleRem = scheduleRem;
	}



	public Schedule(Integer scheduleId, Integer scheduleEmpid,
			String scheduleEmpname, String scheduleSch, Date scheduleBedate,
			Date scheduleEndate, String scheduleRem) {
		super();
		this.scheduleId = scheduleId;
		this.scheduleEmpid = scheduleEmpid;
		this.scheduleEmpname = scheduleEmpname;
		this.scheduleSch = scheduleSch;
		this.scheduleBedate = scheduleBedate;
		this.scheduleEndate = scheduleEndate;
		this.scheduleRem = scheduleRem;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHEDULE.SCHEDULE_ID
     *
     * @return the value of SCHEDULE.SCHEDULE_ID
     *
     * @mbggenerated Wed Jul 09 14:57:48 CST 2014
     */
    public Integer getScheduleId() {
        return scheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHEDULE.SCHEDULE_ID
     *
     * @param scheduleId the value for SCHEDULE.SCHEDULE_ID
     *
     * @mbggenerated Wed Jul 09 14:57:48 CST 2014
     */
    public void setScheduleId(Integer scheduleId) {
        this.scheduleId = scheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHEDULE.SCHEDULE_EMPID
     *
     * @return the value of SCHEDULE.SCHEDULE_EMPID
     *
     * @mbggenerated Wed Jul 09 14:57:48 CST 2014
     */
    public Integer getScheduleEmpid() {
        return scheduleEmpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHEDULE.SCHEDULE_EMPID
     *
     * @param scheduleEmpid the value for SCHEDULE.SCHEDULE_EMPID
     *
     * @mbggenerated Wed Jul 09 14:57:48 CST 2014
     */
    public void setScheduleEmpid(Integer scheduleEmpid) {
        this.scheduleEmpid = scheduleEmpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHEDULE.SCHEDULE_EMPNAME
     *
     * @return the value of SCHEDULE.SCHEDULE_EMPNAME
     *
     * @mbggenerated Wed Jul 09 14:57:48 CST 2014
     */
    public String getScheduleEmpname() {
        return scheduleEmpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHEDULE.SCHEDULE_EMPNAME
     *
     * @param scheduleEmpname the value for SCHEDULE.SCHEDULE_EMPNAME
     *
     * @mbggenerated Wed Jul 09 14:57:48 CST 2014
     */
    public void setScheduleEmpname(String scheduleEmpname) {
        this.scheduleEmpname = scheduleEmpname == null ? null : scheduleEmpname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHEDULE.SCHEDULE_SCH
     *
     * @return the value of SCHEDULE.SCHEDULE_SCH
     *
     * @mbggenerated Wed Jul 09 14:57:48 CST 2014
     */
    public String getScheduleSch() {
        return scheduleSch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHEDULE.SCHEDULE_SCH
     *
     * @param scheduleSch the value for SCHEDULE.SCHEDULE_SCH
     *
     * @mbggenerated Wed Jul 09 14:57:48 CST 2014
     */
    public void setScheduleSch(String scheduleSch) {
        this.scheduleSch = scheduleSch == null ? null : scheduleSch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHEDULE.SCHEDULE_BEDATE
     *
     * @return the value of SCHEDULE.SCHEDULE_BEDATE
     *
     * @mbggenerated Wed Jul 09 14:57:48 CST 2014
     */
    public Date getScheduleBedate() {
        return scheduleBedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHEDULE.SCHEDULE_BEDATE
     *
     * @param scheduleBedate the value for SCHEDULE.SCHEDULE_BEDATE
     *
     * @mbggenerated Wed Jul 09 14:57:48 CST 2014
     */
    public void setScheduleBedate(Date scheduleBedate) {
        this.scheduleBedate = scheduleBedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHEDULE.SCHEDULE_ENDATE
     *
     * @return the value of SCHEDULE.SCHEDULE_ENDATE
     *
     * @mbggenerated Wed Jul 09 14:57:48 CST 2014
     */
    public Date getScheduleEndate() {
        return scheduleEndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHEDULE.SCHEDULE_ENDATE
     *
     * @param scheduleEndate the value for SCHEDULE.SCHEDULE_ENDATE
     *
     * @mbggenerated Wed Jul 09 14:57:48 CST 2014
     */
    public void setScheduleEndate(Date scheduleEndate) {
        this.scheduleEndate = scheduleEndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHEDULE.SCHEDULE_REM
     *
     * @return the value of SCHEDULE.SCHEDULE_REM
     *
     * @mbggenerated Wed Jul 09 14:57:48 CST 2014
     */
    public String getScheduleRem() {
        return scheduleRem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHEDULE.SCHEDULE_REM
     *
     * @param scheduleRem the value for SCHEDULE.SCHEDULE_REM
     *
     * @mbggenerated Wed Jul 09 14:57:48 CST 2014
     */
    public void setScheduleRem(String scheduleRem) {
        this.scheduleRem = scheduleRem == null ? null : scheduleRem.trim();
    }



	@Override
	public String toString() {
		return "Schedule [scheduleId=" + scheduleId + ", scheduleEmpid="
				+ scheduleEmpid + ", scheduleEmpname=" + scheduleEmpname
				+ ", scheduleSch=" + scheduleSch + ", scheduleBedate="
				+ scheduleBedate + ", scheduleEndate=" + scheduleEndate
				+ ", scheduleRem=" + scheduleRem + "]";
	}
    
    
}