package com.icss.oa.folder.pojo;

public class Folder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FOLDER.FOLDER_ID
     *
     * @mbggenerated Wed Jul 02 17:22:35 CST 2014
     */
    private Integer folderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FOLDER.FOLDER_NAME
     *
     * @mbggenerated Wed Jul 02 17:22:35 CST 2014
     */
    private String folderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FOLDER.PARENT_ID
     *
     * @mbggenerated Wed Jul 02 17:22:35 CST 2014
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FOLDER.EMP_ID
     *
     * @mbggenerated Wed Jul 02 17:22:35 CST 2014
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FOLDER.SHARING
     *
     * @mbggenerated Wed Jul 02 17:22:35 CST 2014
     */
    private Integer sharing;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FOLDER.FOLDER_ID
     *
     * @return the value of FOLDER.FOLDER_ID
     *
     * @mbggenerated Wed Jul 02 17:22:35 CST 2014
     */
    public Integer getFolderId() {
        return folderId;
    }

    public Folder() {
		super();
	}

	public Folder(String folderName, Integer parentId, Integer empId,
			Integer sha) {
		super();
		this.folderName = folderName;
		this.parentId = parentId;
		this.empId = empId;
		this.sharing = sha;
	}


	public Folder(Integer folderId, Integer sharing) {
		super();
		this.folderId = folderId;
		this.sharing = sharing;
	}

	public Folder(Integer folderId, String folderName, Integer parentId,
			Integer empId, Integer sharing) {
		super();
		this.folderId = folderId;
		this.folderName = folderName;
		this.parentId = parentId;
		this.empId = empId;
		this.sharing = sharing;
	}

	public Folder(Integer folderId, String folderName) {
		super();
		this.folderId = folderId;
		this.folderName = folderName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FOLDER.FOLDER_ID
     *
     * @param folderId the value for FOLDER.FOLDER_ID
     *
     * @mbggenerated Wed Jul 02 17:22:35 CST 2014
     */
    public void setFolderId(Integer folderId) {
        this.folderId = folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FOLDER.FOLDER_NAME
     *
     * @return the value of FOLDER.FOLDER_NAME
     *
     * @mbggenerated Wed Jul 02 17:22:35 CST 2014
     */
    public String getFolderName() {
        return folderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FOLDER.FOLDER_NAME
     *
     * @param folderName the value for FOLDER.FOLDER_NAME
     *
     * @mbggenerated Wed Jul 02 17:22:35 CST 2014
     */
    public void setFolderName(String folderName) {
        this.folderName = folderName == null ? null : folderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FOLDER.PARENT_ID
     *
     * @return the value of FOLDER.PARENT_ID
     *
     * @mbggenerated Wed Jul 02 17:22:35 CST 2014
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FOLDER.PARENT_ID
     *
     * @param parentId the value for FOLDER.PARENT_ID
     *
     * @mbggenerated Wed Jul 02 17:22:35 CST 2014
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FOLDER.EMP_ID
     *
     * @return the value of FOLDER.EMP_ID
     *
     * @mbggenerated Wed Jul 02 17:22:35 CST 2014
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FOLDER.EMP_ID
     *
     * @param empId the value for FOLDER.EMP_ID
     *
     * @mbggenerated Wed Jul 02 17:22:35 CST 2014
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FOLDER.SHARING
     *
     * @return the value of FOLDER.SHARING
     *
     * @mbggenerated Wed Jul 02 17:22:35 CST 2014
     */
    public Integer getSharing() {
        return sharing;
    }

  
	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FOLDER.SHARING
     *
     * @param sharing the value for FOLDER.SHARING
     *
     * @mbggenerated Wed Jul 02 17:22:35 CST 2014
     */
    public void setSharing(Integer sharing) {
        this.sharing = sharing;
    }
    
    
    @Override
  	public String toString() {
  		return "Folder [folderId=" + folderId + ", folderName=" + folderName
  				+ ", parentId=" + parentId + ", empId=" + empId + ", sharing="
  				+ sharing + "]";
  	}

}