package com.icss.oa.asserts.pojo;

public class Offsup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFSUP.ID
     *
     * @mbggenerated Wed Jul 02 16:56:28 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFSUP.NAME
     *
     * @mbggenerated Wed Jul 02 16:56:28 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFSUP.CATEGORY
     *
     * @mbggenerated Wed Jul 02 16:56:28 CST 2014
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFSUP.SPEC
     *
     * @mbggenerated Wed Jul 02 16:56:28 CST 2014
     */
    private String spec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFSUP.PRICE
     *
     * @mbggenerated Wed Jul 02 16:56:28 CST 2014
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFSUP.COUNT
     *
     * @mbggenerated Wed Jul 02 16:56:28 CST 2014
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFSUP.LOSS
     *
     * @mbggenerated Wed Jul 02 16:56:28 CST 2014
     */
    private Integer loss;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFSUP.ID
     *
     * @return the value of OFFSUP.ID
     *
     * @mbggenerated Wed Jul 02 16:56:28 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFSUP.ID
     *
     * @param id the value for OFFSUP.ID
     *
     * @mbggenerated Wed Jul 02 16:56:28 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFSUP.NAME
     *
     * @return the value of OFFSUP.NAME
     *
     * @mbggenerated Wed Jul 02 16:56:28 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFSUP.NAME
     *
     * @param name the value for OFFSUP.NAME
     *
     * @mbggenerated Wed Jul 02 16:56:28 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFSUP.CATEGORY
     *
     * @return the value of OFFSUP.CATEGORY
     *
     * @mbggenerated Wed Jul 02 16:56:28 CST 2014
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFSUP.CATEGORY
     *
     * @param category the value for OFFSUP.CATEGORY
     *
     * @mbggenerated Wed Jul 02 16:56:28 CST 2014
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFSUP.SPEC
     *
     * @return the value of OFFSUP.SPEC
     *
     * @mbggenerated Wed Jul 02 16:56:28 CST 2014
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFSUP.SPEC
     *
     * @param spec the value for OFFSUP.SPEC
     *
     * @mbggenerated Wed Jul 02 16:56:28 CST 2014
     */
    public void setSpec(String spec) {
        this.spec = spec == null ? null : spec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFSUP.PRICE
     *
     * @return the value of OFFSUP.PRICE
     *
     * @mbggenerated Wed Jul 02 16:56:28 CST 2014
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFSUP.PRICE
     *
     * @param price the value for OFFSUP.PRICE
     *
     * @mbggenerated Wed Jul 02 16:56:28 CST 2014
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFSUP.COUNT
     *
     * @return the value of OFFSUP.COUNT
     *
     * @mbggenerated Wed Jul 02 16:56:28 CST 2014
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFSUP.COUNT
     *
     * @param count the value for OFFSUP.COUNT
     *
     * @mbggenerated Wed Jul 02 16:56:28 CST 2014
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFSUP.LOSS
     *
     * @return the value of OFFSUP.LOSS
     *
     * @mbggenerated Wed Jul 02 16:56:28 CST 2014
     */
    public Integer getLoss() {
        return loss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFSUP.LOSS
     *
     * @param loss the value for OFFSUP.LOSS
     *
     * @mbggenerated Wed Jul 02 16:56:28 CST 2014
     */
    public void setLoss(Integer loss) {
        this.loss = loss;
    }

	public Offsup() {
		super();
	}

	public Offsup(Integer id, String name, String category, String spec,
			Integer price, Integer count, Integer loss) {
		super();
		this.id = id;
		this.name = name;
		this.category = category;
		this.spec = spec;
		this.price = price;
		this.count = count;
		this.loss = loss;
	}

	public Offsup(String name, String category, String spec, Integer price,
			Integer count, Integer loss) {
		super();
		this.name = name;
		this.category = category;
		this.spec = spec;
		this.price = price;
		this.count = count;
		this.loss = loss;
	}

	@Override
	public String toString() {
		return "Offsup [id=" + id + ", name=" + name + ", category=" + category
				+ ", spec=" + spec + ", price=" + price + ", count=" + count
				+ ", loss=" + loss + "]";
	}
    
}