package com.icss.oa.asserts.pojo;

public class Warehouse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WAREHOUSE.WAREHOUSE_ID
     *
     * @mbggenerated Thu Jul 17 12:16:13 CST 2014
     */
    private Integer warehouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WAREHOUSE.WAREHOUSE_NAME
     *
     * @mbggenerated Thu Jul 17 12:16:13 CST 2014
     */
    private String warehouseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WAREHOUSE.WAREHOUSE_TYPE
     *
     * @mbggenerated Thu Jul 17 12:16:13 CST 2014
     */
    private String warehouseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WAREHOUSE.WAREHOUSE_AMOUNT
     *
     * @mbggenerated Thu Jul 17 12:16:13 CST 2014
     */
    private Integer warehouseAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WAREHOUSE.WAREHOUSE_ID
     *
     * @return the value of WAREHOUSE.WAREHOUSE_ID
     *
     * @mbggenerated Thu Jul 17 12:16:13 CST 2014
     */
    public Integer getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WAREHOUSE.WAREHOUSE_ID
     *
     * @param warehouseId the value for WAREHOUSE.WAREHOUSE_ID
     *
     * @mbggenerated Thu Jul 17 12:16:13 CST 2014
     */
    public void setWarehouseId(Integer warehouseId) {
        this.warehouseId = warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WAREHOUSE.WAREHOUSE_NAME
     *
     * @return the value of WAREHOUSE.WAREHOUSE_NAME
     *
     * @mbggenerated Thu Jul 17 12:16:13 CST 2014
     */
    public String getWarehouseName() {
        return warehouseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WAREHOUSE.WAREHOUSE_NAME
     *
     * @param warehouseName the value for WAREHOUSE.WAREHOUSE_NAME
     *
     * @mbggenerated Thu Jul 17 12:16:13 CST 2014
     */
    public void setWarehouseName(String warehouseName) {
        this.warehouseName = warehouseName == null ? null : warehouseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WAREHOUSE.WAREHOUSE_TYPE
     *
     * @return the value of WAREHOUSE.WAREHOUSE_TYPE
     *
     * @mbggenerated Thu Jul 17 12:16:13 CST 2014
     */
    public String getWarehouseType() {
        return warehouseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WAREHOUSE.WAREHOUSE_TYPE
     *
     * @param warehouseType the value for WAREHOUSE.WAREHOUSE_TYPE
     *
     * @mbggenerated Thu Jul 17 12:16:13 CST 2014
     */
    public void setWarehouseType(String warehouseType) {
        this.warehouseType = warehouseType == null ? null : warehouseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WAREHOUSE.WAREHOUSE_AMOUNT
     *
     * @return the value of WAREHOUSE.WAREHOUSE_AMOUNT
     *
     * @mbggenerated Thu Jul 17 12:16:13 CST 2014
     */
    public Integer getWarehouseAmount() {
        return warehouseAmount;
    }

	public void setWarehouseAmount(Integer warehouseAmount) {
		this.warehouseAmount = warehouseAmount;
	}

	public Warehouse(Integer warehouseId, String warehouseName,
			String warehouseType, Integer warehouseAmount) {
		super();
		this.warehouseId = warehouseId;
		this.warehouseName = warehouseName;
		this.warehouseType = warehouseType;
		this.warehouseAmount = warehouseAmount;
	}

	public Warehouse(String warehouseName, String warehouseType,
			Integer warehouseAmount) {
		super();
		this.warehouseName = warehouseName;
		this.warehouseType = warehouseType;
		this.warehouseAmount = warehouseAmount;
	}

	public Warehouse() {
		super();
	}

	@Override
	public String toString() {
		return "Warehouse [warehouseId=" + warehouseId + ", warehouseName="
				+ warehouseName + ", warehouseType=" + warehouseType
				+ ", warehouseAmount=" + warehouseAmount + "]";
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WAREHOUSE.WAREHOUSE_AMOUNT
     *
     * @param warehouseAmount the value for WAREHOUSE.WAREHOUSE_AMOUNT
     *
     * @mbggenerated Thu Jul 17 12:16:13 CST 2014
     */
   

}