package com.icss.hb.po;

// Generated 2014-11-12 16:38:32 by Hibernate Tools 3.4.0.CR1

/**
 * Score generated by hbm2java
 */
public class Score implements java.io.Serializable {

	private ScoreId id;
	private Integer result;

	public Score() {
	}

	public Score(ScoreId id) {
		this.id = id;
	}

	public Score(ScoreId id, Integer result) {
		this.id = id;
		this.result = result;
	}

	public ScoreId getId() {
		return this.id;
	}

	public void setId(ScoreId id) {
		this.id = id;
	}

	public Integer getResult() {
		return this.result;
	}

	public void setResult(Integer result) {
		this.result = result;
	}

}