package com.icss.hb.po;

// Generated 2014-11-12 16:38:32 by Hibernate Tools 3.4.0.CR1

/**
 * ScoreId generated by hbm2java
 */
public class ScoreId implements java.io.Serializable {

	private int sid;
	private int cid;

	public ScoreId() {
	}

	public ScoreId(int sid, int cid) {
		this.sid = sid;
		this.cid = cid;
	}

	public int getSid() {
		return this.sid;
	}

	public void setSid(int sid) {
		this.sid = sid;
	}

	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ScoreId))
			return false;
		ScoreId castOther = (ScoreId) other;

		return (this.getSid() == castOther.getSid())
				&& (this.getCid() == castOther.getCid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSid();
		result = 37 * result + this.getCid();
		return result;
	}

}
