package com.icss.hr.dept.po;

// Generated 2014-3-14 10:47:18 by Hibernate Tools 3.4.0.CR1

/**
 * Dept generated by hbm2java
 */
public class Dept implements java.io.Serializable {

	private Integer deptId;
	private String deptName;
	private String deptLoc;

	public Dept() {
	}

	public Dept(Integer deptId) {
		this.deptId = deptId;
	}

	public Dept(Integer deptId, String deptName, String deptLoc) {
		this.deptId = deptId;
		this.deptName = deptName;
		this.deptLoc = deptLoc;
	}

	public Integer getDeptId() {
		return this.deptId;
	}

	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getDeptLoc() {
		return this.deptLoc;
	}

	public void setDeptLoc(String deptLoc) {
		this.deptLoc = deptLoc;
	}

	@Override
	public String toString() {
		return "Dept [deptId=" + deptId + ", deptName=" + deptName
				+ ", deptLoc=" + deptLoc + "]";
	}

}