package com.icss.hr.admin.po;

// Generated 2014-3-19 9:24:38 by Hibernate Tools 3.4.0.CR1

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private Integer adminId;
	private String adminName;
	private String adminPwd;
	private Integer adminLevel;

	public Admin() {
	}

	public Admin(Integer adminId) {
		this.adminId = adminId;
	}

	public Admin(Integer adminId, String adminName, String adminPwd,
			Integer adminLevel) {
		this.adminId = adminId;
		this.adminName = adminName;
		this.adminPwd = adminPwd;
		this.adminLevel = adminLevel;
	}

	public Integer getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	public String getAdminName() {
		return this.adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	public String getAdminPwd() {
		return this.adminPwd;
	}

	public void setAdminPwd(String adminPwd) {
		this.adminPwd = adminPwd;
	}

	public Integer getAdminLevel() {
		return this.adminLevel;
	}

	public void setAdminLevel(Integer adminLevel) {
		this.adminLevel = adminLevel;
	}

	@Override
	public String toString() {
		return "Admin [adminId=" + adminId + ", adminName=" + adminName
				+ ", adminPwd=" + adminPwd + ", adminLevel=" + adminLevel + "]";
	}
	
}
