package com.icss.oa.bus.pojo;

import java.util.Date;

public class Busrecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUSRECORD.BRECORD_ID
     *
     * @mbggenerated Mon Jul 21 09:11:25 CST 2014
     */
    private Integer brecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUSRECORD.USER_NAME
     *
     * @mbggenerated Mon Jul 21 09:11:25 CST 2014
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUSRECORD.DRIVER
     *
     * @mbggenerated Mon Jul 21 09:11:25 CST 2014
     */
    private String driver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUSRECORD.USE_REASON
     *
     * @mbggenerated Mon Jul 21 09:11:25 CST 2014
     */
    private String useReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUSRECORD.PATH
     *
     * @mbggenerated Mon Jul 21 09:11:25 CST 2014
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUSRECORD.USE_DATE
     *
     * @mbggenerated Mon Jul 21 09:11:25 CST 2014
     */
    private Date startTime;

    private Date endTime;
    
    
    public Busrecord() {
		super();
	}

	public Busrecord(Integer brecordId, String userName, String driver,
			String useReason, String path, Date startTime,Date endTime) {
		super();
		this.brecordId = brecordId;
		this.userName = userName;
		this.driver = driver;
		this.useReason = useReason;
		this.path = path;
		this.setStartTime(startTime);
		this.setEndTime(endTime);
	}

	public Busrecord(String userName, String driver, String useReason,
			String path, Date startTime,Date endTime) {
		super();
		this.userName = userName;
		this.driver = driver;
		this.useReason = useReason;
		this.path = path;
		this.setStartTime(startTime);
		this.setEndTime(endTime);
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUSRECORD.BRECORD_ID
     *
     * @return the value of BUSRECORD.BRECORD_ID
     *
     * @mbggenerated Mon Jul 21 09:11:25 CST 2014
     */
    public Integer getBrecordId() {
        return brecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUSRECORD.BRECORD_ID
     *
     * @param brecordId the value for BUSRECORD.BRECORD_ID
     *
     * @mbggenerated Mon Jul 21 09:11:25 CST 2014
     */
    public void setBrecordId(Integer brecordId) {
        this.brecordId = brecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUSRECORD.USER_NAME
     *
     * @return the value of BUSRECORD.USER_NAME
     *
     * @mbggenerated Mon Jul 21 09:11:25 CST 2014
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUSRECORD.USER_NAME
     *
     * @param userName the value for BUSRECORD.USER_NAME
     *
     * @mbggenerated Mon Jul 21 09:11:25 CST 2014
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUSRECORD.DRIVER
     *
     * @return the value of BUSRECORD.DRIVER
     *
     * @mbggenerated Mon Jul 21 09:11:25 CST 2014
     */
    public String getDriver() {
        return driver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUSRECORD.DRIVER
     *
     * @param driver the value for BUSRECORD.DRIVER
     *
     * @mbggenerated Mon Jul 21 09:11:25 CST 2014
     */
    public void setDriver(String driver) {
        this.driver = driver == null ? null : driver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUSRECORD.USE_REASON
     *
     * @return the value of BUSRECORD.USE_REASON
     *
     * @mbggenerated Mon Jul 21 09:11:25 CST 2014
     */
    public String getUseReason() {
        return useReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUSRECORD.USE_REASON
     *
     * @param useReason the value for BUSRECORD.USE_REASON
     *
     * @mbggenerated Mon Jul 21 09:11:25 CST 2014
     */
    public void setUseReason(String useReason) {
        this.useReason = useReason == null ? null : useReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUSRECORD.PATH
     *
     * @return the value of BUSRECORD.PATH
     *
     * @mbggenerated Mon Jul 21 09:11:25 CST 2014
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUSRECORD.PATH
     *
     * @param path the value for BUSRECORD.PATH
     *
     * @mbggenerated Mon Jul 21 09:11:25 CST 2014
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

	public Date getStartTime() {
		return startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Override
	public String toString() {
		return "Busrecord [brecordId=" + brecordId + ", userName=" + userName
				+ ", driver=" + driver + ", useReason=" + useReason + ", path="
				+ path + ", startTime=" + startTime + ", endTime=" + endTime
				+ "]";
	}


    

    
}