package com.icss.oa.meeting.pojo;

import java.util.Date;

public class Device {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.DEV_ID
     *
     * @mbggenerated Tue Jul 01 14:34:58 CST 2014
     */
    private Integer devId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.DEV_NAME
     *
     * @mbggenerated Tue Jul 01 14:34:58 CST 2014
     */
    private String devName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.DEV_AMOUNT
     *
     * @mbggenerated Tue Jul 01 14:34:58 CST 2014
     */
    private Integer devAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.DEV_AVAILABLE
     *
     * @mbggenerated Tue Jul 01 14:34:58 CST 2014
     */
    private Integer devAvailable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.DEV_PRO
     *
     * @mbggenerated Tue Jul 01 14:34:58 CST 2014
     */
    private String devPro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.DEV_DATE
     *
     * @mbggenerated Tue Jul 01 14:34:58 CST 2014
     */
    private Date devDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.DEV_ID
     *
     * @return the value of DEVICE.DEV_ID
     *
     * @mbggenerated Tue Jul 01 14:34:58 CST 2014
     */
    
    public Device() {
		super();
	}

    
    
    public Device(Integer devId, String devName, Integer devAmount, String devPro, Date devDate,
			Integer devAvailable) {
		super();
		this.devId = devId;
		this.devName = devName;
		this.devAmount = devAmount;
		this.devAvailable = devAvailable;
		this.devPro = devPro;
		this.devDate = devDate;
	}



	public Device(String devName, Integer devAmount,
			String devPro, Date devDate, Integer devAvailable) {
		super();
		this.devName = devName;
		this.devAmount = devAmount;
		this.devAvailable = devAvailable;
		this.devPro = devPro;
		this.devDate = devDate;
	}



	public Integer getDevId() {
        return devId;
    }

   
	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.DEV_ID
     *
     * @param devId the value for DEVICE.DEV_ID
     *
     * @mbggenerated Tue Jul 01 14:34:58 CST 2014
     */
    public void setDevId(Integer devId) {
        this.devId = devId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.DEV_NAME
     *
     * @return the value of DEVICE.DEV_NAME
     *
     * @mbggenerated Tue Jul 01 14:34:58 CST 2014
     */
    public String getDevName() {
        return devName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.DEV_NAME
     *
     * @param devName the value for DEVICE.DEV_NAME
     *
     * @mbggenerated Tue Jul 01 14:34:58 CST 2014
     */
    public void setDevName(String devName) {
        this.devName = devName == null ? null : devName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.DEV_AMOUNT
     *
     * @return the value of DEVICE.DEV_AMOUNT
     *
     * @mbggenerated Tue Jul 01 14:34:58 CST 2014
     */
    public Integer getDevAmount() {
        return devAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.DEV_AMOUNT
     *
     * @param devAmount the value for DEVICE.DEV_AMOUNT
     *
     * @mbggenerated Tue Jul 01 14:34:58 CST 2014
     */
    public void setDevAmount(Integer devAmount) {
        this.devAmount = devAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.DEV_AVAILABLE
     *
     * @return the value of DEVICE.DEV_AVAILABLE
     *
     * @mbggenerated Tue Jul 01 14:34:58 CST 2014
     */
    public Integer getDevAvailable() {
        return devAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.DEV_AVAILABLE
     *
     * @param devAvailable the value for DEVICE.DEV_AVAILABLE
     *
     * @mbggenerated Tue Jul 01 14:34:58 CST 2014
     */
    public void setDevAvailable(Integer devAvailable) {
        this.devAvailable = devAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.DEV_PRO
     *
     * @return the value of DEVICE.DEV_PRO
     *
     * @mbggenerated Tue Jul 01 14:34:58 CST 2014
     */
    public String getDevPro() {
        return devPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.DEV_PRO
     *
     * @param devPro the value for DEVICE.DEV_PRO
     *
     * @mbggenerated Tue Jul 01 14:34:58 CST 2014
     */
    public void setDevPro(String devPro) {
        this.devPro = devPro == null ? null : devPro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.DEV_DATE
     *
     * @return the value of DEVICE.DEV_DATE
     *
     * @mbggenerated Tue Jul 01 14:34:58 CST 2014
     */
    public Date getDevDate() {
        return devDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.DEV_DATE
     *
     * @param devDate the value for DEVICE.DEV_DATE
     *
     * @mbggenerated Tue Jul 01 14:34:58 CST 2014
     */
    public void setDevDate(Date devDate) {
        this.devDate = devDate;
    }



	@Override
	public String toString() {
		return "Device [devId=" + devId + ", devName=" + devName
				+ ", devAmount=" + devAmount + ", devPro=" + devPro 
				+ ", devDate=" + devDate + ", devAvailable=" + devAvailable+ "]";
	}
    
    
}