package com.icss.oa.meeting.pojo;

public class Meetingrecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEETINGRECORD.RECORD_ID
     *
     * @mbggenerated Wed Jul 09 13:59:38 CST 2014
     */
    private Integer recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEETINGRECORD.ORDER_ID
     *
     * @mbggenerated Wed Jul 09 13:59:38 CST 2014
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEETINGRECORD.MEETING_INFO
     *
     * @mbggenerated Wed Jul 09 13:59:38 CST 2014
     */
    private byte[] meetingInfo;

    
    
    public Meetingrecord() {
		super();
	}

	public Meetingrecord(Integer recordId, Integer orderId, byte[] meetingInfo) {
		super();
		this.recordId = recordId;
		this.orderId = orderId;
		this.meetingInfo = meetingInfo;
	}

	public Meetingrecord(Integer orderId, byte[] meetingInfo) {
		super();
		this.orderId = orderId;
		this.meetingInfo = meetingInfo;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEETINGRECORD.RECORD_ID
     *
     * @return the value of MEETINGRECORD.RECORD_ID
     *
     * @mbggenerated Wed Jul 09 13:59:38 CST 2014
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEETINGRECORD.RECORD_ID
     *
     * @param recordId the value for MEETINGRECORD.RECORD_ID
     *
     * @mbggenerated Wed Jul 09 13:59:38 CST 2014
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEETINGRECORD.ORDER_ID
     *
     * @return the value of MEETINGRECORD.ORDER_ID
     *
     * @mbggenerated Wed Jul 09 13:59:38 CST 2014
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEETINGRECORD.ORDER_ID
     *
     * @param orderId the value for MEETINGRECORD.ORDER_ID
     *
     * @mbggenerated Wed Jul 09 13:59:38 CST 2014
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEETINGRECORD.MEETING_INFO
     *
     * @return the value of MEETINGRECORD.MEETING_INFO
     *
     * @mbggenerated Thu Jul 10 12:35:30 CST 2014
     */
    public byte[] getMeetingInfo() {
        return meetingInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEETINGRECORD.MEETING_INFO
     *
     * @param meetingInfo the value for MEETINGRECORD.MEETING_INFO
     *
     * @mbggenerated Thu Jul 10 12:35:30 CST 2014
     */
    public void setMeetingInfo(byte[] meetingInfo) {
        this.meetingInfo = meetingInfo;
    }
   

	@Override
	public String toString() {
		return "Meetingrecord [recordId=" + recordId + ", orderId=" + orderId
				+ ", meetingInfo=" + meetingInfo + "]";
	}
    
    
}