package com.icss.oa.meeting.pojo;

import java.util.Date;

public class Meetingorder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEETINGORDER.ORDER_ID
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEETINGORDER.METTING_NAME
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    private String mettingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEETINGORDER.EMP_ID
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEETINGORDER.ROOM_ID
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    private Integer roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEETINGORDER.ATTEND_PEOPLE
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    private String attendPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEETINGORDER.ATTEND_AMOUNT
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    private Integer attendAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEETINGORDER.START_TIME
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEETINGORDER.END_TIME
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEETINGORDER.DEV_NAME
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    private String devName;
    
    private String aproState;


    
    public Meetingorder() {
		super();
	}

	
	public Meetingorder(Integer orderId, String mettingName, Integer empId,
			Integer roomId, String attendPeople, Integer attendAmount,
			Date startTime, Date endTime, String devName, String aproState) {
		super();
		this.orderId = orderId;
		this.mettingName = mettingName;
		this.empId = empId;
		this.roomId = roomId;
		this.attendPeople = attendPeople;
		this.attendAmount = attendAmount;
		this.startTime = startTime;
		this.endTime = endTime;
		this.devName = devName;
		this.aproState = aproState;
	;
	}


	public Meetingorder(String mettingName, Integer empId, Integer roomId,
			String attendPeople, Integer attendAmount, Date startTime,
			Date endTime, String devName, String aproState) {
		super();
		this.mettingName = mettingName;
		this.empId = empId;
		this.roomId = roomId;
		this.attendPeople = attendPeople;
		this.attendAmount = attendAmount;
		this.startTime = startTime;
		this.endTime = endTime;
		this.devName = devName;
		this.aproState = aproState;
	
	}


	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEETINGORDER.ORDER_ID
     *
     * @return the value of MEETINGORDER.ORDER_ID
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEETINGORDER.ORDER_ID
     *
     * @param orderId the value for MEETINGORDER.ORDER_ID
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEETINGORDER.METTING_NAME
     *
     * @return the value of MEETINGORDER.METTING_NAME
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    public String getMettingName() {
        return mettingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEETINGORDER.METTING_NAME
     *
     * @param mettingName the value for MEETINGORDER.METTING_NAME
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    public void setMettingName(String mettingName) {
        this.mettingName = mettingName == null ? null : mettingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEETINGORDER.EMP_ID
     *
     * @return the value of MEETINGORDER.EMP_ID
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEETINGORDER.EMP_ID
     *
     * @param empId the value for MEETINGORDER.EMP_ID
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEETINGORDER.ROOM_ID
     *
     * @return the value of MEETINGORDER.ROOM_ID
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEETINGORDER.ROOM_ID
     *
     * @param roomId the value for MEETINGORDER.ROOM_ID
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEETINGORDER.ATTEND_PEOPLE
     *
     * @return the value of MEETINGORDER.ATTEND_PEOPLE
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    public String getAttendPeople() {
        return attendPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEETINGORDER.ATTEND_PEOPLE
     *
     * @param attendPeople the value for MEETINGORDER.ATTEND_PEOPLE
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    public void setAttendPeople(String attendPeople) {
        this.attendPeople = attendPeople == null ? null : attendPeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEETINGORDER.ATTEND_AMOUNT
     *
     * @return the value of MEETINGORDER.ATTEND_AMOUNT
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    public Integer getAttendAmount() {
        return attendAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEETINGORDER.ATTEND_AMOUNT
     *
     * @param attendAmount the value for MEETINGORDER.ATTEND_AMOUNT
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    public void setAttendAmount(Integer attendAmount) {
        this.attendAmount = attendAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEETINGORDER.START_TIME
     *
     * @return the value of MEETINGORDER.START_TIME
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEETINGORDER.START_TIME
     *
     * @param startTime the value for MEETINGORDER.START_TIME
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEETINGORDER.END_TIME
     *
     * @return the value of MEETINGORDER.END_TIME
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEETINGORDER.END_TIME
     *
     * @param endTime the value for MEETINGORDER.END_TIME
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEETINGORDER.DEV_NAME
     *
     * @return the value of MEETINGORDER.DEV_NAME
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    public String getDevName() {
        return devName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEETINGORDER.DEV_NAME
     *
     * @param devName the value for MEETINGORDER.DEV_NAME
     *
     * @mbggenerated Tue Jul 08 16:03:49 CST 2014
     */
    public void setDevName(String devName) {
        this.devName = devName == null ? null : devName.trim();
    }


	public String getAproState() {
		return aproState;
	}


	public void setAproState(String aproState) {
		this.aproState = aproState == null ? null : aproState.trim();
	}


	@Override
	public String toString() {
		return "Meetingorder [orderId=" + orderId + ", mettingName="
				+ mettingName + ", empId=" + empId + ", roomId=" + roomId
				+ ", attendPeople=" + attendPeople + ", attendAmount="
				+ attendAmount + ", startTime=" + startTime + ", endTime="
				+ endTime + ", devName=" + devName + ", aproState=" + aproState
				+ "]";
	}



	

	
    
     
}