package com.icss.hr.photo.po;

import com.icss.hr.emp.po.Emp;

// Generated 2014-3-17 12:42:41 by Hibernate Tools 3.4.0.CR1

/**
 * Photo generated by hbm2java
 */
public class Photo implements java.io.Serializable {

	private Integer photoId;
	private String photoPath;
	private Emp emp;

	public Photo() {
	}

	public Photo(Integer photoId) {
		this.photoId = photoId;
	}

	public Photo(String photoPath, Emp emp) {
		super();
		this.photoPath = photoPath;
		this.emp = emp;
	}

	public Photo(Integer photoId, String photoPath, Emp emp) {
		super();
		this.photoId = photoId;
		this.photoPath = photoPath;
		this.emp = emp;
	}

	public Integer getPhotoId() {
		return photoId;
	}

	public void setPhotoId(Integer photoId) {
		this.photoId = photoId;
	}

	public String getPhotoPath() {
		return photoPath;
	}

	public void setPhotoPath(String photoPath) {
		this.photoPath = photoPath;
	}

	public Emp getEmp() {
		return emp;
	}

	public void setEmp(Emp emp) {
		this.emp = emp;
	}

	@Override
	public String toString() {
		return "Photo [photoId=" + photoId + ", photoPath=" + photoPath+ "]";
	}
	
}
